/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

//! \file
//! \brief Header with a target-specific interfaces.
#ifndef EXAMPLE_LED_TARGET_HPP_
#define EXAMPLE_LED_TARGET_HPP_

// All definitions are generated by theCore, so including only this
// header is enough
#include <aux/generated.hpp>

#endif // EXAMPLE_LED_TARGET_HPP_
