//!
//! \file
//! \brief STM32 F4 discovery board with only UART <-> USB adapter attached.
//!
#ifndef TEST_STM32F4DISCOVERY_SIMPLE_TARGET_DEFS_HPP_
#define TEST_STM32F4DISCOVERY_SIMPLE_TARGET_DEFS_HPP_

#endif // TEST_STM32F4DISCOVERY_SIMPLE_TARGET_DEFS_HPP_
